### ISSUE TITLE
Nalu-Wind Test Case

### ISSUE THREAD

**Issue by BumseokLee** [Exawind/exawind-benchmarks#10]
@sbidadi9,
Currently, the IDDES cases are located directly in the nalu-wind directory. 
Can you create a directory for the IDDES cases within the nalu-wind directory and move the files there?

I will also upload 2-D transition cases to the nalu-wind directory soon, and I think organizing the benchmark cases by folder name would be an easy way to keep them sorted.

@mbkuhn 
Any thoughts on this?

**Comment by mbkuhn** [comment]
Thanks for looking at this! I am in the process of moving things around for Shreyas's case. He doesn't have to worry about that. For your case, Bumseok, you can create your own folder in "nalu-wind" that is named after your case. Thanks again!

**Comment by mbkuhn** [comment]
I just pushed some changes. What do you think? Is it in a better place now for you to add to it? I'm still going to make more changes, but the structure is mostly there. @BumseokLee

**Comment by BumseokLee** [comment]
@mbkuhn 
Thanks. Looks great! You can close this ticket!
