### ISSUE TITLE
ABL cases: performance documented

### ISSUE THREAD

**Issue by mbkuhn** [Exawind/exawind-benchmarks#2]
- [ ] rerun cases on cluster (Kestrel) with main long enough to ensure they can be run
- [ ] run 1 (minimum) of the 3 cases long enough to measure quantities of intereset
- [ ] document performance (1 sentence about runtime, resources used) and put both inputs and log files into folder
- [ ] confirm ABL cases are complete for satisfying the milestone

I am envisioning the following:
- each abl case directory will have an inputs/ directory, including the necessary input files and a README that notes the latest version that the input files have been confirmed to work with.
- each abl case that has documented performance will have a performance_doc/ directory, with the log files and the input files used for the latest run. and maybe a plot, but maybe not. It will have a README with a few-sentence synopsis of the machine used, resources used, and wall-clock time taken. The log file should document the number of steps and the git hash + version.

**Comment by moprak-nrel** [comment]
I plan to setup all 3 ABL cases on kestrel this week. Will log the version of code used, and save the run scripts and log files. Will have the postprocessed results available too. All of this will go into the README file.
