### ISSUE TITLE
RANS + transition model airfoil cases with nalu-wind

### ISSUE THREAD

**Issue by mbkuhn** [Exawind/exawind-benchmarks#4]
- [ ] merge transition model PR into nalu-wind master branch
- [ ] add a few relevant cases to new directory within the nalu-wind/ directory
- [ ] rerun cases on cluster (Kestrel) with master long enough to ensure they can be run
- [ ] run 1 (minimum) of the cases long enough to measure quantities of intereset
- [ ] document performance (1 sentence about runtime, resources used) and put both inputs and log files into folder

I am envisioning the following:

-  each airfoil case directory will have an inputs/ directory, including the necessary input files and a README that notes the latest version that the input files have been confirmed to work with.
-  each airfoil case that has documented performance will have a performance_doc/ directory, with the log files and the input files used for the latest run. and maybe a plot, but maybe not. It will have a README with a few-sentence synopsis of the machine used, resources used, and wall-clock time taken. The log file should document the number of steps and the git hash + version.

**Comment by mbkuhn** [comment]
Since these cases rely on a feature that's not in master, I think it would be a good approach to still upload what we do have now and document the status. So, instead of waiting until the first checkbox is complete (merging the feature), let's try to do the rest and state (in the README) the obstacles to running with master. Then, when the feature is merged, we can update the information.

**Comment by BumseokLee** [comment]
@mbkuhn I am closing this ticket!
